language: android
cache: false
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - platform-tools
    - build-tools-21.1.2
    - android-19
    - extra-android-m2repository

script:
     - ./gradlew build compileDebugTestJava
